# Generated by Django 5.2.7 on 2025-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_club_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='faculty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs_photos/'),
        ),
    ]
